runtime: python37
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.85
  max_idle_instances: 1
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

entrypoint: gunicorn -b :$PORT app:app

error_handlers:
- file: app/static/default_error.html

- error_code: over_quota
  file: app/static/over_quota.html

- error_code: dos_api_denial
  file: app/static/dos_api_denial.html

- error_code: timeout
  file: app/static/timeout.html

handlers:
- url: /static
  static_dir: app/static

- url: /favicon\.ico
  secure: always
  static_files: app/static/img/gd_mr_small.ico
  upload: app/static/img/gd_mr_small\.ico
  http_headers:
    X-Robots-Tag: all

- url: /favicon-32x32\.png
  secure: always
  static_files: app/static/img/favicon-32x32.png
  upload: app/static/img/favicon-32x32\.png
  http_headers:
    X-Robots-Tag: all

- url: /humans\.txt
  static_files: app/static/humans.txt
  upload: app/static/humans\.txt
  mime_type: 'text/plain; charset=utf-8'
  http_headers:
    X-Robots-Tag: all

- url: /robots\.txt
  secure: always
  static_files: app/static/robots.txt
  upload: app/static/robots\.txt
  mime_type: 'text/plain; charset=utf-8'
  http_headers:
    X-Robots-Tag: all

- url: /privacy-policy
  static_files: app/static/privacy-policy.html
  upload: app/static/privacy-policy\.html
  mime_type: 'text/html; charset=utf-8'
  http_headers:
    X-Robots-Tag: all

- url: /terms-of-service
  static_files: app/static/terms-of-service.html
  upload: app/static/terms-of-services\.html
  mime_type: 'text/html; charset=utf-8'
  http_headers:
    X-Robots-Tag: all

- url: /admin/.*
  script: auto
  secure: always
  auth_fail_action: unauthorized

- url: .*
  script: auto
  secure: always

